services:
  db:
    image: mysql:8.0
    container_name: events-db
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: events-api
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Variáveis que o Spring Boot mapeará automaticamente
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_DOCKER_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_UPLOAD_DIR: ${APP_UPLOAD_DIR}
    volumes:
      - ./uploads:/app/uploads

volumes:
  db_data:
