spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/api_events_db
spring.datasource.username=montoril
spring.datasource.password=1992
# spring.jpa.hibernate.ddl-auto=update
# Centralização do diretório de uploads
app.upload.dir=uploads/events/