# Spring Boot 2.4+ (e o seu 3.x) consegue importar arquivos externos. No seu arquivo
spring.config.import=optional:file:.env[.properties]
spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# # spring.jpa.hibernate.ddl-auto=update
# Centralização do diretório de uploads
app.upload.dir=${APP_UPLOAD_DIR}

# Oculta detalhes da conexão nos logs
spring.jpa.show-sql=false
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Alterado para acessar swagger em localhost:8080/events
springdoc.swagger-ui.path=/events
