CREATE TABLE IF NOT EXISTS event(
    id CHAR(36) PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    img_url VARCHAR(255) NOT NULL,
    event_url VARCHAR(255) NOT NULL,
    date DATETIME NOT NULL,
    remote BOOLEAN NOT NULL
);